-- ENUM TYPE DEFINITIONS
CREATE TYPE gender AS ENUM ('male', 'female');
CREATE TYPE severity AS ENUM ('mild', 'moderate', 'severe');
CREATE TYPE severity_extended AS ENUM ('mild', 'moderate', 'severe', 'life_threatening');
CREATE TYPE appointment_type AS ENUM ('checkup', 'follow_up', 'specialist', 'emergency', 'therapy');
CREATE TYPE appointment_status AS ENUM ('scheduled', 'completed', 'cancelled', 'missed');
CREATE TYPE question_type AS ENUM ('multiple_choice', 'true_false', 'numerical', 'drawing', 'memory_recall');
CREATE TYPE assessment_status AS ENUM ('in_progress', 'completed', 'abandoned');
CREATE TYPE media_type AS ENUM ('music', 'video', 'photo', 'audio_story');
CREATE TYPE cognitive_domain AS ENUM ('memory', 'attention', 'language', 'executive_function', 'visuospatial', 'mixed');
CREATE TYPE game_type AS ENUM ('quiz', 'flashcard', 'math_exercise');

-- TABLE DEFINITIONS

CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar UNIQUE NOT NULL,
  "phone" varchar UNIQUE,
  "password_hash" varchar NOT NULL,
  "created_at" timestamp DEFAULT now()
);

CREATE TABLE "user_profiles" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer UNIQUE NOT NULL,
  "full_name" varchar NOT NULL,
  "date_of_birth" date,
  "gender" gender,
  "phone" varchar,
  "address" text,
  "city" varchar,
  "hometown" varchar,
  "country" varchar,
  "avatar_url" varchar,
  "emergency_contact" varchar,
  "created_at" timestamp DEFAULT now()
);

CREATE TABLE "emergency_contacts" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "contact_name" varchar NOT NULL,
  "relationship" varchar NOT NULL,
  "phone" varchar NOT NULL,
  "email" varchar,
  "address" text,
  "is_primary" boolean DEFAULT false,
  "created_at" timestamp DEFAULT now()
);

CREATE TABLE "medical_conditions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "condition_name" varchar NOT NULL,
  "diagnosed_date" date,
  "severity" severity,
  "notes" text,
  "is_active" boolean DEFAULT true,
  "created_at" timestamp DEFAULT now()
);

CREATE TABLE "medications" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "medication_name" varchar NOT NULL,
  "dosage" varchar NOT NULL,
  "frequency" varchar NOT NULL,
  "intake_time" varchar,
  "start_date" date NOT NULL,
  "end_date" date,
  "prescribed_by" varchar,
  "prescription_date" date,
  "notes" text,
  "reminder_enabled" boolean DEFAULT true,
  "is_active" boolean DEFAULT true,
  "created_at" timestamp DEFAULT now()
);

CREATE TABLE "allergies" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "allergen" varchar NOT NULL,
  "reaction" text,
  "severity" severity_extended,
  "notes" text,
  "created_at" timestamp DEFAULT now()
);

CREATE TABLE "medical_appointments" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "appointment_type" appointment_type,
  "doctor_name" varchar,
  "hospital_clinic" varchar NOT NULL,
  "department" varchar,
  "appointment_date" timestamp NOT NULL,
  "diagnosis" text,
  "treatment_notes" text,
  "prescription_given" text,
  "next_appointment_date" timestamp,
  "status" appointment_status DEFAULT 'scheduled',
  "created_at" timestamp DEFAULT now(),
  "updated_at" timestamp DEFAULT now()
);

CREATE TABLE "assessment_types" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "description" text,
  "difficulty_level" integer NOT NULL,
  "max_score" integer NOT NULL,
  "passing_score" integer,
  "is_active" boolean DEFAULT true,
  "created_at" timestamp DEFAULT now()
);

CREATE TABLE "assessment_questions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "assessment_type_id" integer NOT NULL,
  "question_text" text NOT NULL,
  "question_type" question_type,
  "options" json,
  "correct_answer" varchar,
  "points" integer DEFAULT 1,
  "order_index" integer
);

CREATE TABLE "user_assessments" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "assessment_type_id" integer NOT NULL,
  "total_score" integer NOT NULL,
  "max_possible_score" integer NOT NULL,
  "percentage_score" decimal(5,2) NOT NULL,
  "difficulty_level" integer NOT NULL,
  "duration_seconds" integer,
  "status" assessment_status DEFAULT 'in_progress',
  "started_at" timestamp DEFAULT now(),
  "completed_at" timestamp,
  "notes" text
);

CREATE TABLE "assessment_answers" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_assessment_id" integer NOT NULL,
  "question_id" integer NOT NULL,
  "user_answer" text,
  "is_correct" boolean,
  "points_earned" integer DEFAULT 0,
  "time_taken_seconds" integer,
  "created_at" timestamp DEFAULT now()
);

CREATE TABLE "important_places" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "place_name" varchar NOT NULL,
  "address" text,
  "description" text,
  "street_view_url" varchar
);

CREATE TABLE "life_events" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "event_title" varchar NOT NULL,
  "event_date" date,
  "description" text
);

CREATE TABLE "favorite_media" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "media_type" media_type,
  "title" varchar NOT NULL,
  "artist" varchar,
  "file_path" varchar
);

CREATE TABLE "ai_clone_videos" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  
  -- Input information
  "reference_text" varchar(500) NOT NULL,
  "target_text" text NOT NULL,
  "language" varchar(20) DEFAULT 'vietnamese',
  "dynamic_scale" decimal(3,2) DEFAULT 1.0,
  
  -- Content generation info (nếu target_text được AI tạo)
  "is_ai_generated_text" boolean DEFAULT false,
  "topic" varchar(200),
  "description" text,
  "keywords" varchar(500),
  
  -- Processing info
  "session_id" varchar(100),
  "status" varchar(20) DEFAULT 'pending',
  
  -- Output info
  "video_url" varchar(500),
  "video_filename" varchar(200),
  "processing_time" decimal(8,2),
  
  -- Error info
  "error_message" text,
  
  -- Timestamps
  "created_at" timestamp DEFAULT now(),
  "updated_at" timestamp DEFAULT now(),
  "completed_at" timestamp
);

CREATE TABLE "cst_game_categories" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "category_name" varchar NOT NULL,
  "description" text,
  "cognitive_domain" cognitive_domain,
  "difficulty_levels" integer DEFAULT 3,
  "is_active" boolean DEFAULT true
);

CREATE TABLE "cst_games" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "category_id" integer NOT NULL,
  "game_name" varchar NOT NULL,
  "game_type" game_type,
  "difficulty_level" integer DEFAULT 1,
  "instructions" text,
  "game_config" json NOT NULL,
  "thumbnail_url" varchar,
  "estimated_play_time_minutes" integer,
  "is_active" boolean DEFAULT true
);

CREATE TABLE "user_game_sessions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "game_id" integer NOT NULL,
  "session_score" integer,
  "max_possible_score" integer,
  "accuracy_percentage" decimal(5,2),
  "completion_time_seconds" integer,
  "difficulty_level" integer,
  "hints_used" integer DEFAULT 0,
  "status" assessment_status DEFAULT 'in_progress',
  "started_at" timestamp DEFAULT now(),
  "completed_at" timestamp
);

CREATE TABLE "game_session_details" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "session_id" integer NOT NULL,
  "question_index" integer,
  "user_response" text,
  "correct_answer" text,
  "is_correct" boolean,
  "response_time_seconds" integer,
  "points_earned" integer,
  "created_at" timestamp DEFAULT now()
);

-- INDEX
CREATE INDEX ON "user_assessments" ("user_id", "completed_at");

-- FOREIGN KEYS
ALTER TABLE "user_profiles" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
ALTER TABLE "emergency_contacts" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
ALTER TABLE "medical_conditions" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
ALTER TABLE "medications" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
ALTER TABLE "allergies" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
ALTER TABLE "medical_appointments" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
ALTER TABLE "assessment_questions" ADD FOREIGN KEY ("assessment_type_id") REFERENCES "assessment_types" ("id");
ALTER TABLE "user_assessments" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
ALTER TABLE "user_assessments" ADD FOREIGN KEY ("assessment_type_id") REFERENCES "assessment_types" ("id");
ALTER TABLE "assessment_answers" ADD FOREIGN KEY ("user_assessment_id") REFERENCES "user_assessments" ("id");
ALTER TABLE "assessment_answers" ADD FOREIGN KEY ("question_id") REFERENCES "assessment_questions" ("id");
ALTER TABLE "important_places" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
ALTER TABLE "life_events" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
ALTER TABLE "favorite_media" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
ALTER TABLE "ai_clone_videos" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
ALTER TABLE "cst_games" ADD FOREIGN KEY ("category_id") REFERENCES "cst_game_categories" ("id");
ALTER TABLE "user_game_sessions" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
ALTER TABLE "user_game_sessions" ADD FOREIGN KEY ("game_id") REFERENCES "cst_games" ("id");
ALTER TABLE "game_session_details" ADD FOREIGN KEY ("session_id") REFERENCES "user_game_sessions" ("id");
