version: "3.9"

x-common: &common
  restart: always
  env_file:
    - .env

x-common-volumes: &common-volumes
  volumes:
    - ./app:/app/app
    - ./alembic:/app/alembic
    - ./requirements.txt:/app/requirements.txt
    - ./.env:/app/.env
    - ./static:/app/static
    - ./app_clone:/app/app_clone

services:
  db:
    image: postgres:16
    <<: *common
    volumes:
      - ./mount-data/db:/var/lib/postgresql/data
    ports:
      - 5678:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 10

  alembic:
    build:
      context: .
      dockerfile: Dockerfile
    <<: 
      - *common
      - *common-volumes
    command: [ "alembic", "upgrade", "head" ]
    restart: "no"
    depends_on:
      db:
        condition: service_healthy


  app:
    build:
      context: .
      dockerfile: Dockerfile
    <<: 
      - *common
      - *common-volumes
    ports:
      - 8777:8777
    command: [ "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8777", "--workers", "4" ]
    depends_on:
      db:
        condition: service_healthy
      alembic:
        condition: service_completed_successfully
